name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--verbose"
          jupyter: true

      - name: Run isort
        uses: isort/isort-action@v1
        with:
            requirements-files: "requirements.txt"