name: Release

on:
  push:
    branches:
      - github_actions_integration

      
  workflow_run:
    workflows: ["Tests", "Lint"]
 
jobs:
  

  release:
    
    if: github.actor .repository_owner == 'kezif'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python
        run: |  
          python.exe -m pip install --upgrade pip |
          pip install hatch  
        
      #- name: Install Requirements
      #  if: ${{ hashFiles('requirements.txt') != '' }}
      #  run: python -m venv venv |
      #    source venv/bin/activate |
      #    pip install -r requirements.txt


  
      - name: Bump Version
        run: |
          if [ ${{contains(github.event.head_commit.message, '#major') }}]; then
            hatch version major
          elif [  ${{contains(github.event.head_commit.message, '#minor') }}]; then
            hatch version minor
          else
            hatch version fix
          fi
        shell: bash

      - name: Push git tag
        id: push-git-tag
        run: |
          NEW_TAG=$(echo hatch version)
          git tag $NEW_TAG
          git push origin $NEW_TAG
        shell: bash


      - name: Build package
        run: |
          hatch build 

      - name: Publish package on TestPyPI
        run: hatch publish -r test
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.TEST_PYPI_API_TOKEN }}

      #- name: Publish the release notes
      #  uses: release-drafter/release-drafter@v5
      #  with:
      #    publish: ${{ steps.push-git-tag.outputs.NEW_TAG != '' }}
      #    tag: ${{ steps.push-git-tag.outputs.NEW_TAG }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}